# -*- coding: utf-8 -*-
"""machin.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hi_Mmvt7VAej5DEZE3WRWntQC1xH04MJ
"""

# 데이터 전처리 및 분할
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
class Dataset():
  def __init__(self,X,y,random_state = 42,scaled=True):
    self.X = X
    self.y = y
    self.random_state = random_state
    self.scaled = scaled
    self.split()
  def split(self):
    X = self.X
    y = self.y
    scaled = self.scaled
    random_state = self.random_state
    x_train,x_test,y_train,y_test = train_test_split(X,y,random_state=random_state)
    if scaled:
      ss = StandardScaler()
      ss.fit(x_train)
      x_train = ss.transform(x_train)
      x_test = ss.transform(x_test)
    self.x_train = x_train
    self.x_test = x_test
    self.y_train = y_train
    self.y_test = y_test

import numpy as np
if __name__ == '__main__':
  X = np.arange(100).reshape(-1,1)    
  y = np.zeros(100)
  data = Dataset(X,y)
  print(data.x_train.shape)

